name: CI

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project 
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run Solhint
        run: |
          npm install -g solhint
          solhint 'src//*.sol'  

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        with:
          target: '.'
          fail-on: medium

      - name: Run Coverage and Filter
        run: |
          sudo apt-get install lcov -y

          forge coverage --report lcov --ir-minimum
          
          lcov --remove lcov.info 'script/*' 'test/*' --ignore-errors unused -o filtered-lcov.info
          
          lcov --list filtered-lcov.info > filtered_summary.txt
          
          COVERAGE=$(grep "Total:" filtered_summary.txt | grep -oE "[0-9]+\.[0-9]+" | head -1 | cut -d'.' -f1)
          
          echo "Actual Logic Coverage: $COVERAGE%"
          
          if [ -z "$COVERAGE" ] || [ "$COVERAGE" -lt 90 ]; then
            echo "Error: Coverage is too low or no source files found!"
            exit 1
          fi

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report.md

      - name: Write Summary
        run: cat coverage_report.md >> $GITHUB_STEP_SUMMARY