name: CI

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project 
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run Solhint
        run: |
          npm install -g solhint
          solhint 'src//*.sol'  

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        with:
          target: '.'
          fail-on: medium

      - name: Run Coverage and Check Threshold
        run: |
          forge coverage --report summary --no-match-path "{test,script}/*.sol" > coverage_report.md
          COVERAGE=$(grep "Total" coverage_report.md | awk '{print $3}' | cut -d'.' -f1)
          if [ "$COVERAGE" -lt 90 ]; then
            echo "Coverage is below 90% ($COVERAGE%)"
            exit 1
          fi

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report.md

      - name: Write Summary
        run: cat coverage_report.md >> $GITHUB_STEP_SUMMARY